SANDBOX_SOURCES=\
	luabind/sb_luabind.cpp\
	luabind/sb_luabind_metatable.cpp\
	luabind/sb_luabind_ref.cpp\
	luabind/sb_luabind_stack.cpp\
	luabind/sb_luabind_wrapper.cpp\
	meta/sb_meta.cpp\
	sb_accelerometer.cpp\
	sb_animation.cpp\
	sb_application.cpp\
	sb_atlaser.cpp\
	sb_background.cpp\
	sb_bitmap_font.cpp\
	sb_clear_scene.cpp\
	sb_container.cpp\
	sb_container_blend.cpp\
	sb_container_color.cpp\
	sb_container_shader.cpp\
	sb_container_transform.cpp\
	sb_container_transform3d.cpp\
	sb_container_viewport.cpp\
	sb_container_visible.cpp\
	sb_controller_bidirect.cpp\
	sb_controller_elastic.cpp\
	sb_controller_map.cpp\
	sb_controller_phase.cpp\
	sb_controller_split.cpp\
	sb_event_function.cpp\
	sb_fill_rect.cpp\
	sb_font.cpp\
	sb_graphics.cpp\
	sb_label.cpp\
	sb_log.cpp\
	sb_lua.cpp\
	sb_luabind_controller.cpp\
	sb_luabind_math.cpp\
	sb_luabind_resources.cpp\
	sb_luabind_scene.cpp\
	sb_math.cpp\
	sb_object_proxy.cpp\
	sb_particles.cpp\
	sb_particles_bind.cpp\
	sb_particles_blocks.cpp\
	sb_processor.cpp\
	sb_resources.cpp\
	sb_scene.cpp\
	sb_scene_object.cpp\
	sb_shader.cpp\
	sb_sprite.cpp\
	sb_tcb_spline2d.cpp\
	sb_threads_mgr.cpp\
	sb_touch_info.cpp\
	sb_utf.cpp\
	sb_widget.cpp

LUA_SOURCES=\
	lapi.c\
	lauxlib.c\
	lbaselib.c\
	lbitlib.c\
	lcode.c\
	lcorolib.c\
	lctype.c\
	ldblib.c\
	ldebug.c\
	ldo.c\
	ldump.c\
	lfunc.c\
	lgc.c\
	llex.c\
	lmathlib.c\
	lmem.c\
	loadlib.c\
	lobject.c\
	lopcodes.c\
	lparser.c\
	lstate.c\
	lstring.c\
	lstrlib.c\
	ltable.c\
	ltablib.c\
	ltm.c\
	lundump.c\
	lvm.c\
	lzio.c
